global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flaskblog"
    static_configs:
      - targets: ["54.173.120.204:5000"]

  - job_name: "flaskbloglocal"
    static_configs:
      - targets: ["flaskblog-1:5000"]