name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install Pipfile
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

  test:
    runs-on: windows-latest
    needs: build
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install Pipfile
          pip install -r requirements.txt

      - name: Start Flask app
        run: |
          python app.py &
        env:
          FLASK_ENV: development

      - name: Run tests
        run: |
          pip install pytest
          pip install pytest-playwright
          playwright install
          pytest ./tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.AWS_EC2_HOST }}
          USER: ubuntu
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > mykey.pem
          chmod 400 mykey.pem

          ssh -o StrictHostKeyChecking=no -i "mykey.pem" $USER@$HOST << 'EOF'
            cd ./flaskSREFINAL
            git pull origin main
            pip3 install -r requirements.txt --break-system-packages
          EOF
